out_dir: "crystallm_v1_small"  # the path to the directory containing the trained model
start: FILE:prompts/my_prompt.txt  # the prompt; can also specify a file, use as: "FILE:prompt.txt"
num_samples: 2  # number of samples to draw
max_new_tokens: 3000  # number of tokens generated in each sample
temperature: 0.8  # 1.0 = no change, < 1.0 = less random, > 1.0 = more random, in predictions
top_k: 10  # retain only the top_k most likely tokens, clamp others to have 0 probability
seed: 1337
device: "cuda"  # examples: 'cpu', 'cuda', 'cuda:0', 'cuda:1', etc.
dtype: "bfloat16"  # 'float32' or 'bfloat16' or 'float16'
compile: False  # use PyTorch 2.0 to compile the model to be faster
target: file  # where the generated content will be sent; can also be 'file'
generated_dir: test_generated_cifs #Directory of Cif files